#!/usr/bin/env zsh
set -e

echo "Removing library in 5....."
sleep 1
echo "4...."
sleep 1
echo "3..."
sleep 1
echo "2.."
sleep 1
echo "1."
sleep 1

echo "Removing library..."
rm -rf ../Library/*

echo "Regenerating 'Reviews/Cancer' library..."
mkdir -p ../Library/Reviews/Cancer
./regen_lib.py ./source_data/library.bib ./source_data/review_cancer.csv "../Library/Reviews/Cancer"

echo "Regenerating 'Reviews/Non Cancer' library..."
mkdir -p "../Library/Reviews/Non cancer"
./regen_lib.py ./source_data/library.bib ./source_data/review_noncancer.csv "../Library/Reviews/Non cancer/"

echo "Regenerating 'Articles' library..."
mkdir "../Library/Research Articles"
./regen_lib.py ./source_data/library.bib ./source_data/articles.csv "../Library/Research Articles/"

echo "Done!"
